spring:
  application:
    name: supermercasdo

  # Configuración de la Base de Datos PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/sistema_comercial
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver
    
  # Configuración de JPA/Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true 
        # NOTA: PostgreSQLDialect es a menudo deducido automáticamente
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
# Configuración del Servidor Web
server: 
  port: 9090

